#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | cron:help)
    help_content_func () {
      declare desc="return help_content string"
      cat<<help_content
    cron:build <app>, builds cron for <app>"
    cron:rebuild, rebuild crons for all apps
help_content
    }

    if [[ $1 = "cron:help" ]] ; then
        echo -e 'Usage: dokku cron[:[re]build] [<app>]'
        echo ''
        echo 'Example:'
        echo ''
        echo '$ dokku cron:build example'
        echo 'Building cron for example'
        echo ''
        echo 'Additional commands:'
        help_content_func | sort | column -c2 -t -s,
    else
        help_content_func
    fi
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
